### ISSUE TITLE
Elaborate the definitions.md file 

### ISSUE THREAD

**Issue by bananas24** [basesdepatos/notes#45]
Create a folder named `unit1`, and a file `definitions.md`.
In the `definitions.md` file, with title: `Definition and examples` explain the following concepts>

File types and formats, with 10 examples
Unicode
XML
ASCII
Binary file

**Comment by AlexWhut** [comment]
Finalizado. Done !

**Comment by bananas24** [comment]
@AlexWhut I do not see the related PR. Please ping me when done

**Comment by Alexandra024** [comment]
hay que linkear la issue de esta tarea  y hacer un PR

**Comment by AlexWhut** [comment]
Tengo abierto todavia el PR anterior, entonces lo actualice, y aproveche y etiquete de que la tarea esta terminada

**Comment by bananas24** [comment]
@AlexWhut don't miss the PR's
The one you opened before is for your username to be incorporated into the contributors file.
This is a different task that should be done in small groups. See the four participants here and ask them for detailed instructions:
![image](https://github.com/user-attachments/assets/f062b459-4f1f-4555-b7d1-3bfb44107cc3)
Aaaaand, no Spanish here :face_with_head_bandage:
