### ISSUE TITLE
Create the other.md file

### ISSUE THREAD

**Issue by bananas24** [basesdepatos/notes#52]
Create a folder named `unit1`, and a file `other.md`
In the `other`.md file, explain the following concepts:

- DML
- DDL
- DCL
- TCL

Codd's 12 rules

SQL injection

**Comment by YuUs01** [comment]
@symn369 DML
@Sosoloogic DDL
@tamasi17 DCL Codd's 12 rules
@YuUs01 TCL SQL injection

**Comment by tamasi17** [comment]
Covered DCL and Codd's Rules in my last commit. 
Ordered the info on each concept so it is similar to the main issue.


Some format info in Markdown documents:
# header 1 has one #
## header two has 2 ##

**everything between double asterisks will be bold**


(@symn369 @Sosoloogic @YuUs01)

**Comment by tamasi17** [comment]
@Sosoloogic if you already have the **notes** repository cloned in your computer:

in your GitBash command line interface go to the notes folder (using ** cd ** to move)

![image](https://github.com/user-attachments/assets/cc0071a0-21c1-43a5-a00c-0418415b87e4)

** git pull origin main ** updates your local repo to the last version in main
** git pull origin add_other ** updates your local repo to the last version in our branch, add_other

you should now have a new **unit1** folder with the ** other.md ** doc.
(you can confirm this typing **ls**)

open other.md and once you have added what DDL means, save the document.

if you type ** git status ** there should be changes to commit !

** git add .\unit1\ **  this lets you stage the changes you want to commit
** git commit -m "ici ton message genre j'ai fait ça et ça" **  this records the changes and a message about the work done
** git push origin add_other **  this pushes all the changes you just did !!

in Github you'll be able to see your work is done <3
